### ISSUE TITLE
Cannot find where used the ListView.

### ISSUE THREAD

**Issue by xiaoliwe** [JustinXinLiu/SwipeableSplitView#4]
noticed that "ListView has been replaced with ListBox for better performance and styling" . 
but , i cannot find any where used it in source code . that's missing ? or other things ? 

BTW: 
you point that "A new property IsPanSelectorEnabled (well proabably badly named :p) has been..." . 
i searched all the projects and not find any where used it , would you like to point ? 

thanks a lot.

**Comment by JustinXinLiu** [comment]
Read it carefully. No `ListView` is used, it's replaced by a `ListBox`.

Also, `IsPanSelectorEnabled` is clearly in the [source code](https://github.com/JustinXinLiu/SwipeableSplitView/blob/master/GestureDemo/SwipeableSplitView.cs#L214) too...

**Comment by xiaoliwe** [comment]
understand , thanks .
interesting, my demo code is not working that used **IsPanSelectorEnabled**  property by panning up/down on the bottom area of the left pane .  i think panning up/down feature to use in **Shell.xaml** file and style key is  **MenuListBoxItemStyle**  , correct ?

**Comment by JustinXinLiu** [comment]
It only uses the style to highlight the item. The feature itself is done inside the custom control.

Check [this line](https://github.com/JustinXinLiu/SwipeableSplitView/blob/480faf5a40fe5b8ad9ed6cd97c516bb43c888856/GestureDemo/SwipeableSplitView.cs#L342) of code.
